version: '3.9'
networks:
  deploy-dev:
    driver: bridge
services:
  app: 
    container_name: deploy-orderservice
    build: 
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Post
      POSTGRES_DB: OrdersDb
    ports:
      - "5432:5432"
    networks:
      - deploy-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data  
volumes:
  postgres-data:

